// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa10nPhLRKTywz6V89jHeuHc-3raD1aU0',
    appId: '1:949919542824:web:0a6c21821c7edb41878f1d',
    messagingSenderId: '949919542824',
    projectId: 'familytree-b4d81',
    authDomain: 'familytree-b4d81.firebaseapp.com',
    storageBucket: 'familytree-b4d81.firebasestorage.app',
    measurementId: 'G-BRTQJFZXR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCKHHmPE80ljU-N0dSYWuXrlkEoxvc9cc',
    appId: '1:183688357375:android:5973baae52397eed27f3ca',
    messagingSenderId: '183688357375',
    projectId: 'familyroot-26df8',
    storageBucket: 'familyroot-26df8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMjf3eqMLz73izYPHRf-7jZBXUjnFgrY',
    appId: '1:183688357375:ios:4bd476c0e9aa8e9e27f3ca',
    messagingSenderId: '183688357375',
    projectId: 'familyroot-26df8',
    storageBucket: 'familyroot-26df8.firebasestorage.app',
    androidClientId: '183688357375-2ncomgs94in409vvh7d4lh3psp43413r.apps.googleusercontent.com',
    iosClientId: '183688357375-r9lkuejo0aui71m7odcgj3mbeuit4n8u.apps.googleusercontent.com',
    iosBundleId: 'com.sdlfamilyroot2026',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnDb_bNcTp7E-u8YyZHKV7XXYWWOIMXF0',
    appId: '1:949919542824:ios:cdc175dec8c955d9878f1d',
    messagingSenderId: '949919542824',
    projectId: 'familytree-b4d81',
    storageBucket: 'familytree-b4d81.firebasestorage.app',
    androidClientId: '949919542824-pcvvgdc5ssd59obdjomq17eh8dkei927.apps.googleusercontent.com',
    iosClientId: '949919542824-vf9c0tgn4dofjddegp2stf0etrl5rqrb.apps.googleusercontent.com',
    iosBundleId: 'com.familyrootsdl2026.familyRoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa10nPhLRKTywz6V89jHeuHc-3raD1aU0',
    appId: '1:949919542824:web:c81fd5e393fe54a2878f1d',
    messagingSenderId: '949919542824',
    projectId: 'familytree-b4d81',
    authDomain: 'familytree-b4d81.firebaseapp.com',
    storageBucket: 'familytree-b4d81.firebasestorage.app',
    measurementId: 'G-CGP9JDX22P',
  );
}
